name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente?'
        required: true
        default: 'Desenvolvimento'
        type: choice
        options:
          - Desenvolvimento
          - Homologação
          - Produção
      projectName:
        description: 'Nome da Pasta?'
        required: true
        default: 'cf_xxxx'
        type: string
      destroy:
        description: 'Destruir CF?'
        required: true
        default: 'False'
        type: choice
        options:
          - True
          - False
          
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      branch_key: ${{ github.event.inputs.environment == 'Desenvolvimento' && 'develop' || github.event.inputs.environment == 'Homologação' && 'homolog' || github.event.inputs.environment == 'Produção' && 'main' }}
      env_prefix: ${{ github.event.inputs.environment == 'Desenvolvimento' && 'dev' || github.event.inputs.environment == 'Homologação' && 'hmg' || github.event.inputs.environment == 'Produção' && 'prd' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Verify Environment
        run: |
          echo "Projeto: ${{ github.event.inputs.projectName }}"
          echo "Branch: ${{ github.ref }}"
          echo "Ambiente selecionado: ${{ env.env_prefix }}"
          echo "Destroy: ${{ github.event.inputs.destroy }}"
          if [ "${{ github.event.inputs.environment }}" == "Produção" ] && [ "${{ github.ref }}" != "refs/heads/main" ]; then 
            echo "Atenção: Produção obrigatoriamente precisa partir da branch main!"
            exit 1
          fi